include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    sort_pub_dependencies: false
    one_member_abstracts: false
    use_decorated_box: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
