name: fake_commerce_firebase
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.3.0"


dependencies:
  flutter:
    sdk: flutter

  #state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^8.1.0

  #navigation
  auto_route: ^5.0.1

  #core
  equatable: ^2.0.5

  #firebase
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6
  google_sign_in: ^5.4.1

  #ui
  flex_color_scheme: ^5.1.0
  carousel_slider: ^4.1.1
  font_awesome_flutter: ^10.1.0

  #utility
  path_provider: ^2.0.11



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  #code geneneration
  build_runner: ^2.2.0
  auto_route_generator: 5.0.1



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
